BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "balena-imx8m-var-dart"
BBFILE_PATTERN_balena-imx8m-var-dart := "^${LAYERDIR}/"
BBFILE_PRIORITY_balena-imx8m-var-dart = "1337"

LAYERSERIES_COMPAT_balena-imx8m-var-dart = "scarthgap"

# Mask recipes which we do not use and cause build failure
BBMASK += "meta-imx/meta-imx-bsp/recipes-multimedia/pipewire"
BBMASK += "meta-imx/meta-imx-bsp/recipes-multimedia/wireplumber"
BBMASK += "meta-imx/meta-imx-bsp/recipes-security"
BBMASK += "meta-variscite-bsp-common/recipes-multimedia/bluealsa"
BBMASK += "meta-variscite-bsp-imx/dynamic-layers/fsl-bsp-release/recipes-multimedia/pipewire"

#BBMASK += "/meta-fsl-bsp-release/imx/meta-bsp/recipes-browser "
#BBMASK += "/meta-freescale/recpes-graphics"
#BBMASK += "/meta-variscite-imx/recipes-core/packagegroup"
#BBMASK += "/meta-freescale/dynamic-layers"
#BBMASK += "/meta-freescale/recipes-multimedia"
#BBMASK += "/meta-variscite-bsp/recipes-core/base-files/base-files"
#BBMASK += "/meta-variscite-bsp/recipes-connectivity/bluealsa/bluealsa_git.bbappend"
#BBMASK += "/meta-openembedded/meta-oe/recipes-kernel/broadcom-bt-firmware/broadcom-bt-firmware_12.0.1.1105_p3.bb"
#BBMASK += "/meta-variscite-bsp/recipes-multimedia/gstreamer/"
#IMAGE_INSTALL:remove = "fsl-rc-local"

# When adding imx8mm-var-som, the Variscite layer
# appended the ttymxc3 serial console to the imx8mm
# machine conf, see meta-variscite-imx commit 6dc1db0b.
# On our side, this caused agetty to interfere in the chip's
# communication with brcm_patchram_plus thus making BT fail.
SERIAL_CONSOLES:imx8mm-var-dart = "115200;ttymxc0"
SERIAL_CONSOLES:imx8mm-var-som = "115200;ttymxc3"

FIRMWARE_COMPRESSION:imx8m-var-dart ?= "1"
FIRMWARE_COMPRESSION:imx8mm-var-dart ?= "1"

# This custom device-tree is used for
# imx8mm-var-dart only.
KERNEL_DEVICETREE:append:imx8mm-var-dart = " \
    freescale/imx8mm-var-dart-dt8mcustomboard_p1atlas-pps-v1.dtb \
    freescale/imx8mm-var-dart-dt8mcustomboard-legacy_p1atlas-pps-v1.dtb \
"

# we need only the kernel with the initramfs in the rootfs so we remove the non-initramfs version
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "kernel-image"

# Reduces the size of packages shared between the main rootfs and the initramfs.
CFLAGS:append:pn-busybox = " -Os"
CFLAGS:append:pn-bash = " -Os"
CFLAGS:append:pn-coreutils = " -Os"
CFLAGS:append:pn-util-linux = " -Os"
CFLAGS:append:pn-e2fsprogs = " -Os"
CFLAGS:append:pn-dosfstools = " -Os"
CFLAGS:append:pn-parted = " -Os"
CFLAGS:append:pn-mtools = " -Os"
CFLAGS:append:pn-shadow = " -Os"
CFLAGS:append:pn-kmod = " -Os"
CFLAGS:append:pn-xz = " -Os"
CFLAGS:append:pn-zlib = " -Os"
CFLAGS:append:pn-zstd = " -Os"
CFLAGS:append:pn-openssl = " -Os"
CFLAGS:append:pn-gmp = " -Os"
CFLAGS:append:pn-libcap = " -Os"
CFLAGS:append:pn-libseccomp = " -Os"
CFLAGS:append:pn-libbsd = " -Os"
CFLAGS:append:pn-libmd = " -Os"
CFLAGS:append:pn-libxcrypt = " -Os"
CFLAGS:append:pn-onig = " -Os"
CFLAGS:append:pn-ncurses = " -Os"
CFLAGS:append:pn-readline = " -Os"
CFLAGS:append:pn-acl = " -Os"
CFLAGS:append:pn-attr = " -Os"
CFLAGS:append:pn-jq = " -Os"
